id: AD9AD32F3
title: DharmakÄya Transference
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:25:10.201695
  last_modified_at: 2022-03-01 06:25:10.201698
