id: AD9AD32F3
title: A Simple Method of Transference for Helpless Animals
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:25:10.198569
  last_modified_at: 2022-03-01 06:25:10.198575
