id: AD9AD32F3
title: 'Transference: Enlightenment Without Meditation (root text)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:25:10.204431
  last_modified_at: 2022-03-01 06:25:10.204436
