id: AD9AD32F3
title: A Simple Practice of Phowa, 'Transference of Consciousness'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:25:10.200306
  last_modified_at: 2022-03-01 06:25:10.200310
