id: AD9AD32F3
title: 'Transference: Enlightenment Without Meditation (Compilation)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:25:10.202975
  last_modified_at: 2022-03-01 06:25:10.202978
